lnnrtwttkhn/recipes

recipes/tiramisu.qmd

minor fixes in tiramisu recipe

---

recipes/chocolate-cake-kids.qmd

finally add chocolate recipe
fix #6

add chocolate cake recipe for kids, fix #6

---

recipes/noodles.qmd

added noodles recipe

---

recipes/black-forest-cherry-dessert.qmd
recipes/chocolate-cake-kids.qmd

two recipes were still in german.
this adds a translation.

translate german recipes

---

recipes/lentil-bolognese.qmd

add recipe for lentil bolognese, fix #20

---

recipes/tiktok-ramen.qmd

Add new recipe for tiktok ramen

---

recipes/fesenjan.qmd

Add new recipe for Fesenjan (Iranian Stew)

---

recipes/banana_brownies.qmd

Banana brownies recipe

---

Gyoza.qmd

add Gyoza Recipe

---

recipes/CinnamonRolls.qmd

Add new recipe for Cinnamon Rolls

---

recipes/cup_of_sugar.qmd

Added recipe for cup of sugar

---

recipes/vegan_brownies.qmd

Add new recipe for vegan brownies to Quarto

---

recipes/Avocado-Toast.qmd

Avocado-Toast

---

recipes/pasta-alla-norma.qmd

Hey Lennart,
here is a big recommendation!
Fix #76

Pasta alla Norma recipe added

---

recipes/veganpizza.qmd

add vegan pizza recipe

---

recipes/poke_bowl.qmd

Hey, take a look into my new recipe. If you want, you can add it to your recipes :) Enjoy!

Added Poke Bowl Recipe 

---

recipes/granola.qmd

#57 
Here is a recipe for granola.

Add new recipe for granola

---

recipes/Potato-salad.qmd

Add potato salad recipe

---

recipes/JuliusR.qmd

Mein Hähnchenfilet-Rezept

---

recipes/peanut_udon.qmd

Please add this amazing recipe for peanut udon

Add peanut udon recipe

---

recipes/IndianDal.qmd

add new recipe: IndianDal

---

recipes/bananabread-annabel.qmd

add bananabread recipe

---

recipes/KababDigi.qmd

Hi,
I just added KababDidi recipe for issue.
fixed #109

KebabDigi recipe added

---

recipes/aGreatEvening.qmd

I doesn't get better than this

Maurizios recipe for a great evening

---

recipes/banoffe-pie.qmd

recipe of a banoffe pie 
Fixes #126

Banoffe Pie :) yum yum

---

recipes/Sarmale.qmd

his PR adds a traditional Romanian Sarmale recipe following the repository guidelines.

Add Romanian Sarmale recipe

---

recipes/pear-chocolate-chip-muffins.qmd

Closes #113 
This pull request includes a new recipe for pear chocolate chip muffins.

Add pear chocolate chip muffins
